r1 = Role.create(character_name: "Mad Max")
r2 = Role.create(character_name: "Iron Man")
r3 = Role.create(character_name: "Wonder Woman")
r4 = Role.create(character_name: "Princess Mia")

a1 = Audition.create(actor: "Benny", location: "Los Angeles", phone: 5558978, hired: false, role: r1)
a2 = Audition.create(actor: "Alex", location: "Los Angeles", phone: 5558978, hired: false, role: r1)
a3 = Audition.create(actor: "James", location: "Los Angeles", phone: 5558978, hired: false, role: r1)
a4 = Audition.create(actor: "George", location: "Los Angeles", phone: 5558978, hired: false, role: r2)
a5 = Audition.create(actor: "Ryan", location: "Los Angeles", phone: 5558978, hired: false, role: r2)
a6 = Audition.create(actor: "Camila", location: "Los Angeles", phone: 5558978, hired: false, role: r3)
a7 = Audition.create(actor: "Stacy", location: "New York", phone: 5558978, hired: false, role: r3)
a8 = Audition.create(actor: "Paola", location: "New York", phone: 5558978, hired: false, role: r4)
a9 = Audition.create(actor: "Jane", location: "New York", phone: 5558978, hired: false, role: r4)